# Generated by Django 4.2.4 on 2023-08-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ME2NModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_commande", models.DateField(verbose_name="Date de commande")),
                (
                    "num_commande",
                    models.CharField(max_length=200, verbose_name="Numéro commande"),
                ),
                (
                    "code_article",
                    models.CharField(max_length=200, verbose_name="Code article"),
                ),
                (
                    "designation",
                    models.CharField(max_length=200, verbose_name="Designation"),
                ),
                ("quantite", models.FloatField(verbose_name="Quantité")),
                ("devise", models.CharField(max_length=200, verbose_name="Devise")),
                ("prix", models.FloatField(verbose_name="Prix")),
                ("valeur", models.FloatField(verbose_name="Valeur")),
                (
                    "fournisseur",
                    models.CharField(max_length=200, verbose_name="Fournisseur"),
                ),
            ],
        ),
    ]
