"""
Django settings for Django_Plotly project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from decouple import config
from pathlib import Path
import os
import django_heroku
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'resume',
    'ckeditor',
    'taggit',
    'contact',
    'dataviz_try',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_Plotly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Django_Plotly.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default':{
        'ENGINE':'django.db.backends.postgresql_psycopg2',
        'NAME': config('POSTGRE_NAME', default=""),
        'USER': config('POSTGRE_USER', default=""),
        'PASSWORD': config('POSTGRE_PASSWORD', default=""),
        'HOST': config('POSTGRE_HOST', default=""),
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# # En local
# STATIC_URL = '/static/' # Naming the url pattern
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR,"staticfiles"),
# ] # for searching other statics somewhere in whole project

# STATIC_ROOT = os.path.join(BASE_DIR,'static_cdn') # for deployement with collectstatic

# MEDIA_URL = '/media/' # Naming the url pattern

# MEDIA_ROOT = os.path.join(BASE_DIR,'mediafiles') # where media will be stored after upload (dev)


# Amazon AWS S3 config
AWS_ACCESS_KEY_ID = config('AWS_PUBLIC_ACCESS_KEY', default="NO_KEY")
AWS_SECRET_ACCESS_KEY = config('AWS_PRIVATE_ACCESS_KEY', default="NO_KEY")
AWS_STORAGE_BUCKET_NAME = 's3-django-dataviz-bucket'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {'CacheControl' : 'max-age=86400'}

AWS_S3_FILE_OVERWRITE = False 
AWS_DEFAULT_ACL = None

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR,"staticfiles"),
# ] # for searching other statics somewhere in whole project

AWS_LOCATION = 'static'
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
STATICFILES_STORAGE = 'Django_Plotly.storage_backends.StaticStorage'

# s3 public media settings
PUBLIC_MEDIA_LOCATION = 'media'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
DEFAULT_FILE_STORAGE = 'Django_Plotly.storage_backends.PublicMediaStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# taggit
TAGGIT_CASE_INSENSITIVE = True

# ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        'removePlugins':'stylesheetparser',
        'allowedContent': True,
        }
    }

# sendemail
# EMAIL_BACKEND = 'django.core.mail.backend.smtp.Emailbackend'
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')

# HEROKU CONFIG
django_heroku.settings(locals(), staticfiles=False)
    